### PR TITLE
Upgrade to latest DynamoDB local and default stdout to pipe when running tests or standalone app

### PR DESCRIPTION
**Pull request by themucha**
I attempted to update the package to use the latest DynamoDB Local release, but the [latest commit](https://github.com/Medium/local-dynamo/commit/7f5b74d22b7ec85b3db42e018e81a490ce144911) defaulted stdio to ignore in spawn calls, which broke ```npm test``` and the standalone app for me.

### CODE REVIEW

**Comment by xiao** [comment]
Hey @themucha, thanks for the contribution. Could you please sign the CLA at https://github.com/Medium/opensource?

**Comment by themucha** [comment]
@xiao see https://github.com/Medium/opensource/pull/69
Thanks!

**Comment by xiao** [comment]
Thanks for signing the CLA!

 * Could you remove the `aws_dynamodb_local_old` directory in https://github.com/themucha/local-dynamo/commit/6817e0ae73d3056183eb9e0457b432d9091802f6?
 * Could you squash the two commits, https://github.com/themucha/local-dynamo/commit/bf21fc91f54b9fd76c38fda680e873520bddadbc and https://github.com/themucha/local-dynamo/commit/1c884e40b7d0399f58d36b94ed1fe2ac26145b06?

Other than that, the change LGTM!

**Comment by themucha** [comment]
- Removed aws_dynamodb_local_old. Sorry about that.
- Squashed the two commits, as requested.

Thanks for taking the time to review the change!

**Pull request closed without merging**
